### PR TITLE
Revamp packaging for 2.9 (take 2)

### PR DESCRIPTION
**Pull request by amercader**
Follow up from #18

### CODE REVIEW

**Comment by kowh-ai** [comment]
@amercader - great! - much appreciated! - I have the new branch (_kowh-ai-Revamp-Packaging-for-2.9_) now set up in my local GitHub Desktop and vscode. I'll start again on this tomorrow morning

**Comment by amercader** [comment]
@kowh-ai With the 2.9 packages I am at the stage of the install where I need to restart the server and I've realized that uWSGI is still not running. I see that the package installed the `/etc/supervisor/conf.d/ckan-uswgi.conf` file but AFAICT supervisor is not yet installed in the system. Do you install it manually? (ie is this a step I need to add to the install instructions?)

**Comment by kowh-ai** [comment]
@amercader - yes! - I install supervisor separately (`sudo apt-get install supervisor`). I then run the `sudo service supervisor restart`. I was thinking this step would be cleared up in the deployment docs (https://docs.ckan.org/en/latest/maintaining/installing/deployment.html) - however it would probably be better in the install docs

**Comment by kowh-ai** [comment]
@amercader - there may be a permission problem on `/usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/` - not sure the best approach is here - I normally just open up this directory (777) but maybe this needs to be taken care of in the `after_web.j2` file

**Comment by amercader** [comment]
@kowh-ai ok, thanks. I think we need to add as part of the package install docs. You should not require the deployment ones when installing from package.
Can you jump to gitter for a moment? It will be easier

**Comment by amercader** [comment]
@kowh-ai I've pushed some changes to install datapusher properly, could you give it a go?
I still need to check the py2 install, and there is a chance that it might conflict with the 2.7 and 2.8 installs but at this point I'm leaning towards building 2.7 and 2.8 with the current scripts (master) that we know work and focus on 2.9 onwards for these PR.

**Comment by kowh-ai** [comment]
> @kowh-ai I've pushed some changes to install datapusher properly, could you give it a go?

@amercader  - Yes I'll run a new test (CKAN 2.9 / py3 / focal) on a brand new focal instance now

**Comment by kowh-ai** [comment]
@amercader Testing a brand new install (CKAN 2.9 / py3 / focal)

`sudo apt install -y libpq5 redis-server git nginx supervisor` **ok**

`sudo dpkg -i python-ckan_2.9.0b-py3-focal1_amd64.deb` 

ModuleNotFoundError: No module named 'distutils.core'

`sudo apt-get install python3-distutils` **ok**

`sudo dpkg -i python-ckan_2.9.0b-py3-focal1_amd64.deb`

**ERROR: You need to specify the CKAN config (.ini) file path.**

**Use the --config parameter or set environment variable CKAN_INI**
**or have one of ckan.ini, development.ini in the current directory.**

Looks like the **config file generation** line fails in the `after_web.j2` script

Will keep digging

**Comment by amercader** [comment]
@kowh-ai The ckan.ini error should be fixed now with the latest dev-v2.9 branch, so if you rebuild the package you should be good. I added extra step to the install docs on https://github.com/ckan/ckan/pull/5511 (let's not merge it yet)

I'm not getting this, but I'll try again to see if I can reproduce it:

```
ModuleNotFoundError: No module named 'distutils.core'

sudo apt-get install python3-distutils ok
```

**Comment by kowh-ai** [comment]
> @kowh-ai The ckan.ini error should be fixed now with the latest dev-v2.9 branch, so if you rebuild the package you should be good

@amercader - yes the `sudo dpkg -i python-ckan_2.9.0b-py3-focal1_amd64.deb` works now

**Comment by kowh-ai** [comment]
@amercader - had to restart supervisor a couple of times but it works...

For this test "Check that a view was created and data is on the DataStore (green button)" I just get a 'hang' in the browser now so the Datapusher setup has changed...could be me so will keep plugging away at my config...

**Comment by kowh-ai** [comment]
@amercader - still unsuccessful with Datapusher (CKAN 2.9/py3/focal) but the package install all looks good (supervisor/uwsgi)...I think it's just me...will keep on it as I need to learn the datapusher/datastore extensions

**Comment by amercader** [comment]
@kowh-ai DataPusher won't work until https://github.com/ckan/ckan/pull/5520 is merged to 2.9. You can apply the changes locally and it should work fine:

```
cd /usr/lib/ckan/default/src/ckan
sudo wget https://github.com/ckan/ckan/pull/5520.diff
sudo patch -p1 < 5520.diff
sudo supervisorctl restart all
```

I've just finished testing 2.9 + focal + py3 / py2 and I'm happy with these. Can you test 2.9 + bionic? Use the commands above until that PR is not merged

**Comment by kowh-ai** [comment]
@amercader - OK great thanks for DataPusher update instructions! and yes I will set up a CKAN 2.9 bionic test now

**Comment by kowh-ai** [comment]
@amercader - 2.9 + bionic + py2 (package install) - **all good** - however, still the same DataPusher problem after patching on both bionic and 2.9/focal/py3 - I'll keep digging

**Comment by amercader** [comment]
@kowh-ai quick question, what solr / tomcat version are you using on bionic? `dpkg -l | grep tomcat`
Or are you using `solr-jetty`

**Comment by amercader** [comment]
@kowh-ai I gave up trying to support 2.7 and 2.8 as well given the changes recently made. Let's just use the current version of the scripts (tag `build-ckan-2.8`) for building 2.7 and 2.8. If for some reason we need to modify the scripts we can create a branch. Once we merge this to master we will use to build 2.9 (and future versions)

**Comment by kowh-ai** [comment]
OK @amercader fine with me

**Comment by kowh-ai** [comment]
@amercader - let me know what testing etc I can help with over the next 3 days

**Pull request merged**
