### PR TITLE
Update scripts for next CKAN 2.10.0 / 2.9.8 release

### PR DESCRIPTION
**Pull request by amercader**
For the next release I think we should target the following:

| CKAN version | Ubuntu version | Python version |
| --- | --- | --- |
| 2.9 | 20.04 (focal) | Python 3 |
| 2.10 | 20.04 (focal) | Python 3 |
| 2.10 | 22.04 (jammy) | Python 3 |

Included in this PR

* Updated the build scripts to remove old Ubuntu targets 
* Remove py2 support
* Consolidate and simplify build scripts
* Upgrade fpm version

### CODE REVIEW

**Comment by kowh-ai** [comment]
@amercader I'll try to run package builds on a new Ubuntu 20.04 VM. I'll let you know how I go.

**Comment by amercader** [comment]
Testing update:


| CKAN version | Ubuntu version | Success | Notes |
| --- | --- | --- | --- |
| 2.9 | 20.04 (focal) | :heavy_check_mark:  | All good with the current instructions |
| 2.10 | 20.04 (focal) | Pending |
| 2.10 | 22.04 (jammy) | :heavy_check_mark: | Docs needed some rework: https://github.com/ckan/ckan/pull/7390 |

**Comment by kowh-ai** [comment]
> @amercader I'll try to run package builds on a new Ubuntu 20.04 VM. I'll let you know how I go.

@amercader - I had a multitude of issues getting _any_ package built on my new Ubuntu 20.04 virtual machine last week. Decided to pull the pin and concentrate on the new Docker stuff...apologies for this :-(

**Comment by amercader** [comment]
@kowh-ai no worries! I think these are reasonably solid to go

**Review by kowh-ai — APPROVED** [review]

**Pull request merged**
