### PR TITLE
Use Docker to build the deb packages

### PR DESCRIPTION
**Pull request by amercader**
This replaces the old Ansible / Vagrant setup with Docker. All the building steps are run in the relevant `ubuntu:X.Y` image, and the resulting deb package is copied to the client host. As with the old scripts, you can pass build args to control the process. The full command is:

```
docker buildx build \
    --output type=local,dest=.  \
    --build-arg CKAN_VERSION=2.11 \
    --build-arg CKAN_BRANCH=dev-v2.11 \
    --build-arg DATAPUSHER_VERSION=0.0.21 \
    --build-arg DISTRIBUTION=noble \
    --build-arg UBUNTU_VERSION=24.04 \
    .
```

For now we are sticking with a single Dockerfile for all Ubuntu versions as there is only one minor difference in focal, but if there are more differences added in the future we will switch to different Dockerfiles.

All the target combinations for the next release build fine, full script below for reference:

| CKAN version | Ubuntu version |
| ------------ | -------------- |
| 2.10         | 20.04 (focal)  |
| 2.10         | 22.04 (jammy)  |
| 2.11         | 22.04 (jammy)  |
| 2.11         | 24.04 (noble)  |

TODO:

- [x]  Adapt `ckan-package` helper script
- [x] Finish README
- [x] Automate via actions
- [x] Publish packages (as a Github release and / or s3 packaging.ckan.org )

```
docker buildx build --output type=local,dest=./output --build-arg CKAN_VERSION=2.10 --build-arg CKAN_BRANCH=dev-v2.10 --build-arg DATAPUSHER_VERSION=0.0.21 --build-arg DISTRIBUTION=focal --build-arg ITERATION=1 --build-arg UBUNTU_VERSION=20.04 .

docker buildx build --output type=local,dest=./output --build-arg CKAN_VERSION=2.10 --build-arg CKAN_BRANCH=dev-v2.10 --build-arg DATAPUSHER_VERSION=0.0.21 --build-arg DISTRIBUTION=jammy --build-arg ITERATION=1 --build-arg UBUNTU_VERSION=22.04 .

docker buildx build --output type=local,dest=./output --build-arg CKAN_VERSION=2.11 --build-arg CKAN_BRANCH=dev-v2.11 --build-arg DATAPUSHER_VERSION=0.0.21 --build-arg DISTRIBUTION=jammy --build-arg ITERATION=1 --build-arg UBUNTU_VERSION=22.04 .

docker buildx build --output type=local,dest=./output --build-arg CKAN_VERSION=2.11 --build-arg CKAN_BRANCH=dev-v2.11 --build-arg DATAPUSHER_VERSION=0.0.21 --build-arg DISTRIBUTION=noble --build-arg ITERATION=1 --build-arg UBUNTU_VERSION=24.04 .
```

### CODE REVIEW

**Comment by kowh-ai** [comment]
Wonderful wonderful work here @amercader! I have quickly built 4 debian packages on my Mac OS machine:

Here are the branches I have built (just to test)

1. dev-v2.11 (noble)
2. dev-v2.11 (jammy)
3. ckan-2.10.4 (jammy)
4. ckan-2.10.4 (focal)

Screenshot 2024-07-24 at 1 39 47 pm
I'm happy to test these debian packages on fresh VM's if you want me to.

I can further test and merge after you finish the TODO above _or_ when give me the word

**Comment by kowh-ai** [comment]
Testing of deb packages

- [ ] dev-v2.10 on focal (Ubuntu 20.04)
- [x] dev-v2.10 on jammy (Ubuntu 22.04)
- [ ] dev-v2.11 on jammy (Ubuntu 22.04)
- [ ] dev-v2.11 on noble (Ubuntu 24.04)

**Comment by kowh-ai** [comment]
@amercader - had an issue installing dev-v2.11 on jammy. Seems the file: `/usr/lib/ckan/default/lib/python3.10/site-packages/ckanext/activity/subscriptions.py` incurred some corruption:

Screenshot 2024-07-25 at 1 55 48 pm

I tried a brand new VM and re-built this debian package but I got the same result. 

To fix I just removed the corrupted lines in the `subscriptions.py` file...after that everything was all hunky dory

I'll continued with the others now

**Comment by amercader** [comment]
That's really weird. This looks like a merge error but the HEAD at the dev-v2.11 branch doesn't have these lines:

https://github.com/ckan/ckan/blob/dev-v2.11/ckanext/activity/subscriptions.py#L167

These lines were removed 3 weeks ago:

https://github.com/ckan/ckan/commit/af60df951b34a6dcda3c1cba4fd1b364fff940e6

Try using --no-cache when building to see if that helps

**Comment by kowh-ai** [comment]
Yes the `--no-cache` option seems to fix this corruption. Previously I ran a `docker system prune` and when building the deb package looked like it was compiling/installing everything from scratch again...but maybe it wasn't..

**Comment by kowh-ai** [comment]
@amercader - Looks to be a problem with running `dev-v2.11` on noble (Ubuntu 24.04)

the deb package for noble includes Python **3.12** which has a problem with `find_module`

This is the error:

Screenshot 2024-07-28 at 12 45 24 pm

I'll see if I can work out how to include (build) Python **3.11** in the package rather than **3.12**

**Comment by amercader** [comment]
This again looks like a caching issue. The py 3.12 compatibility issue with `loader.find_module()` was fixed in https://github.com/ckan/ckan/pull/8357, and backported to `dev-v2.11` (https://github.com/ckan/ckan/pull/8368), meaning that the fix is in the `dev-v2.11` branch.

Docker with cache the `RUN git clone ...` step, which is fine when we are using tags but problematic when targeting the release branch. We could use some of the hacks described [here](https://stackoverflow.com/questions/36996046/how-to-prevent-dockerfile-caching-git-clone) but for now it's just easier to always use  `--no-cache`.

**Comment by kowh-ai** [comment]
@amercader - OK, I thought I had used the `--no-cache` option in my Makefile but then again maybe I didn't...Good to see Python 3.12 can remain...thanks

**Comment by amercader** [comment]
This is now complete.

There are two new GitHub workflows:

* `build.yml` builds the deb packages (based on the versions supplied in `VERSIONS.json`) and stores them as artifacfts in the workflow run page. This is triggered on every push.
Screenshot 2024-12-09 at 11-41-37 Remove sed · ckan_ckan-packaging@1408f03


* Additionally, when a tag is pushed, `publish.yml` also builds the packages and:
   1. Uploads them to the S3 bucket powering https://packaging.ckan.org
   2. Creates a new GitHub release with the packages attached as asset

Screenshot 2024-12-09 at 11-42-40 Remove sed · ckan_ckan-packaging@1408f03


Screenshot 2024-12-09 at 11-32-36 Releases · ckan_ckan-packaging

**Pull request merged**
